### ISSUE TITLE
Multiple cards selected while voting

### ISSUE THREAD

**Issue by dbeuchler** [Toxantron/scrumonline#61] opened 2017-06-08 10:06 UTC
![img_0459](https://user-images.githubusercontent.com/920832/26921354-152cf8a4-4c3c-11e7-8fea-75a6714cbb3e.JPG)

**Comment by Toxantron** [comment] 2017-06-08 15:30
Can you reproduce it?

**Comment by dbeuchler** [comment] 2017-06-15 17:51
Not on iOS Safari, maybe a user with Android Chrome?

**Comment by Toxantron** [comment] 2017-06-15 20:19
I have an idea. Maybe on a slow network a user selected a new card before the server responded. I will check the code if that could be the case.

**Comment by Toxantron** [comment] 2017-06-19 07:41
This could be fixed in the Members Controller in main.is

Instead of resetting the UI directly when selecting a card we should await the servers response and then handle the different situations properly:
1. One card selected and response was success. (default)
2. Already one confirmed but user changes mind and new card is accepted as well.
3. User changed selection but the new card was not accepted because the poll was already completed (highlight the confirmed one green, leave the new one red)
4. User (quickly) selected two cards and receives delayed responses. (similar to 3, but make sure the above bug is gone)

**Closed** 2017-07-15 05:39 UTC
Labels: bug
