### ISSUE TITLE
Errors with Annotation on install

### ISSUE THREAD

**Issue by TheGorf** [Toxantron/scrumonline#98] opened 2019-02-25 19:47 UTC
I am using the latest code here on Github cloned to my webserver.  I've setup a small AMI2 instance on Amazon and the requirements covered as far as I can tell from the documentation.  

I followed the install. Setup my config and then I ran the bin/composer install command without any issues:

Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 16 installs, 0 updates, 0 removals
  - Installing symfony/polyfill-mbstring (v1.10.0): Downloading (100%)
  - Installing psr/log (1.1.0): Downloading (100%)
  - Installing symfony/debug (v3.0.9): Downloading (100%)
  - Installing symfony/console (v2.8.49): Downloading (100%)
  - Installing doctrine/event-manager (v1.0.0): Downloading (100%)
  - Installing doctrine/cache (v1.8.0): Downloading (100%)
  - Installing doctrine/dbal (v2.9.2): Downloading (100%)
  - Installing doctrine/collections (v1.5.0): Downloading (100%)
  - Installing doctrine/orm (v2.4.8): Downloading (100%)
  - Installing symfony/polyfill-ctype (v1.10.0): Downloading (100%)
  - Installing symfony/yaml (v2.8.49): Downloading (100%)
  - Installing guzzlehttp/promises (v1.3.1): Downloading (100%)
  - Installing ralouphie/getallheaders (2.0.5): Downloading (100%)
  - Installing psr/http-message (1.0.1): Downloading (100%)
  - Installing guzzlehttp/psr7 (1.5.2): Downloading (100%)
  - Installing guzzlehttp/guzzle (6.3.3): Downloading (100%)
symfony/polyfill-mbstring suggests installing ext-mbstring (For best performance)
symfony/console suggests installing psr/log-implementation (For using the console logger)
symfony/console suggests installing symfony/event-dispatcher ()
symfony/console suggests installing symfony/process ()
doctrine/cache suggests installing alcaeus/mongo-php-adapter (Required to use legacy MongoDB driver)
Writing lock file
Generating autoload files

but when I go to create the database config it throws quite a few errors:

$ ./vendor/bin/doctrine orm:generate-proxies
PHP Fatal error:  Uncaught Error: Class 'Doctrine\Common\Annotations\AnnotationRegistry' not found in /home/ec2-user/scrumonline/vendor/doctrine/orm/lib/Doctrine/ORM/Configuration.php:152
Stack trace:
#0 /home/ec2-user/scrumonline/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php(71): Doctrine\ORM\Configuration->newDefaultAnnotationDriver(Array, true)
#1 /home/ec2-user/scrumonline/src/bootstrap.php(11): Doctrine\ORM\Tools\Setup::createAnnotationMetadataConfiguration(Array)
#2 /home/ec2-user/scrumonline/cli-config.php(3): require_once('/home/ec2-user/...')
#3 /home/ec2-user/scrumonline/vendor/doctrine/orm/bin/doctrine.php(48): require('/home/ec2-user/...')
#4 /home/ec2-user/scrumonline/vendor/doctrine/orm/bin/doctrine(4): include('/home/ec2-user/...')
#5 {main}
  thrown in /home/ec2-user/scrumonline/vendor/doctrine/orm/lib/Doctrine/ORM/Configuration.php on line 152

There is no "Doctrine" directory:
$ ll
total 76
drwxrwxr-x 2 ec2-user ec2-user    22 Feb 25 19:41 bin
-rwxrwxr-x 1 ec2-user ec2-user   187 Feb 25 19:41 build.sh
-rw-rw-r-- 1 ec2-user ec2-user   142 Feb 25 19:41 cli-config.php
-rw-rw-r-- 1 ec2-user ec2-user   182 Feb 25 19:41 composer.json
-rw-r--r-- 1 root     root     33876 Feb 25 19:45 composer.lock
drwxrwxr-x 2 ec2-user ec2-user   259 Feb 25 19:41 doc
drwxrwxr-x 2 ec2-user ec2-user   241 Feb 25 19:41 docker
-rwxrwxr-x 1 ec2-user ec2-user  1938 Feb 25 19:41 docker.sh
-rw-rw-r-- 1 ec2-user ec2-user 11357 Feb 25 19:41 LICENSE.md
-rw-rw-r-- 1 ec2-user ec2-user  3232 Feb 25 19:41 README.md
drwxrwxr-x 8 ec2-user ec2-user  4096 Feb 25 19:44 src
drwxrwxr-x 2 ec2-user ec2-user    50 Feb 25 19:41 vagrant
-rw-rw-r-- 1 ec2-user ec2-user   562 Feb 25 19:41 Vagrantfile
drwxr-xr-x 9 root     root       130 Feb 25 19:45 vendor

**Comment by Toxantron** [comment] 2019-02-26 08:55
Sorry you are having trouble with the installation. Doctrine should be in the vendor directory. The only thing that stands out as far as I can see is that your vendor directory is owned by root.

**Comment by Toxantron** [comment] 2019-04-06 19:35
This seems to be a duplicate of #102 and is probable caused by a version mismatch. I added my working composer.lock that hopefully resolves your issue.

**Comment by Toxantron** [comment] 2019-04-07 16:40
Probably solved together with #102.

**Closed by Toxantron** 2019-04-07 16:40 UTC
